FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .
RUN pip install --upgrade pip && apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu113

COPY . .
