defaults:
  - _self_
  - logger: tensorboard
  - model: resnet18
  - metric: f1_score
  - optimizer: adamw
  - criterion: cross_entropy
  - augmentations: audio_light
  - trainer: vision_trainer
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  seed: 42
  device: cuda
  n_epochs: 20
  batch_size: 256
  n_workers: 4
  amp: true
  save_scripted_model: true
  project_dir: ${hydra:runtime.cwd}
  checkpoint_path: weights
  artifacts_dir: ${general.project_dir}/logs/cv_train_logs
  run_name: ${now:%Y-%m-%d_%H-%M-%S}

data:
  dataset_name: training.data.emospeech.EmoSpeech
  datapath: ${general.project_dir}/data/emotions_audio
  label2id:
    angry: 0
    contempt: 1
    disgust: 2
    fear: 3
    happy: 4
    sad: 5
    surprise: 6
    neutral: 7

hydra:
  run:
    dir: ${general.artifacts_dir}/${general.run_name}
  sweep:
    dir: ${general.artifacts_dir}/${general.run_name}
    subdir: ${hydra.job.override_dirname}
