defaults:
  - _self_
  - logger: tensorboard
  - model: resnet18
  - metric: f1_score
  - optimizer: adamw
  - criterion: cross_entropy
  - augmentations: null
  - trainer: vision_trainer
  - datamodule: audio_classification
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  seed: 42
  device: cuda
  n_epochs: 60
  batch_size: 512
  n_workers: 4
  audio_len: 64000 # 4 sec
  sample_rate: 16000
  amp: true
  save_scripted_model: true
  project_dir: ${hydra:runtime.cwd}
  checkpoint_path: weights
  artifacts_dir: ${general.project_dir}/logs/cv_train_logs
  run_name: ${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${general.artifacts_dir}/${general.run_name}
  sweep:
    dir: ${general.artifacts_dir}/${general.run_name}
    subdir: ${hydra.job.override_dirname}
